const coreLifecycleSkills = (prefix, provider, executable) => [
  {
    name: `${prefix}-setup`,
    provider,
    syntax: `$${prefix}-setup [--json]`,
    dispatcher: `setup --provider ${prefix}`,
    purpose: `Probe the ${executable} executable and structured-output session support.`,
    note: 'Read-only; it does not start a delegated model turn.',
  },
  {
    name: `${prefix}-doctor`,
    provider,
    syntax: `$${prefix}-doctor [permission flags] [--json]`,
    dispatcher: `doctor --provider ${prefix}`,
    purpose: 'Preflight exact resume, workspace access, and headless permission policy.',
    note: 'Headless jobs cannot hand an interactive permission prompt to a live terminal.',
  },
  {
    name: `${prefix}-delegate`,
    provider,
    syntax: `$${prefix}-delegate [provider flags] -- "task prompt"`,
    dispatcher: `delegate --provider ${prefix}`,
    purpose: `Start one supervised ${provider} structured-output job.`,
    note: `The driver invokes ${executable} and records the exact session ID.`,
  },
  {
    name: `${prefix}-status`,
    provider,
    syntax: `$${prefix}-status [--job <id>] [--all] [--json] [--compact]`,
    dispatcher: `status --provider ${prefix}`,
    purpose: `List ${provider} jobs or inspect one supervised process.`,
    note: 'Status reads plugin-owned records and reconciles the supervisor process.',
  },
  {
    name: `${prefix}-wait`,
    provider,
    syntax: `$${prefix}-wait <jobId> [--timeout 5m] [--interval 2s] [--json] [--compact]`,
    dispatcher: 'wait',
    purpose: 'Wait for the supervised turn to finish, fail, stop, or time out.',
    note: 'A timeout leaves the provider process supervised.',
  },
  {
    name: `${prefix}-result`,
    provider,
    syntax: `$${prefix}-result <jobId> [--partial] [--json] [--compact]`,
    dispatcher: 'result',
    purpose: 'Read normalized final output or an explicitly requested partial result.',
    note: 'The latest completed turn is returned after exact-session follow-up.',
  },
  {
    name: `${prefix}-stop`,
    provider,
    syntax: `$${prefix}-stop <jobId> [--all] [--json] [--compact]`,
    dispatcher: 'stop',
    purpose: `Terminate a supervised ${provider} job and persist the stopped state.`,
    note: 'Stopped jobs remain inspectable.',
  },
  {
    name: `${prefix}-followup`,
    provider,
    syntax: `$${prefix}-followup <jobId> [--all] [--json] -- "next instruction"`,
    dispatcher: 'followup',
    purpose: `Resume the exact ${provider} session captured for a job.`,
    note: 'Never uses a workspace-global recent-session selector.',
  },
];

export const codexSkills = [
  {
    name: 'claude-setup',
    provider: 'Claude Code',
    syntax: '$claude-setup',
    dispatcher: 'setup',
    purpose: 'Check the basic Codex, Node.js, Claude Code, transcript, and follow-up environment.',
    note: 'Read-only. An aggregate warn can be healthy when only the optional Claude daemon probe warns.',
  },
  {
    name: 'claude-doctor',
    provider: 'Claude Code',
    syntax:
      '$claude-doctor [--claude-access] [--real|--chrome|--no-chrome] [permission flags] [--json]',
    dispatcher: 'doctor',
    purpose:
      'Preflight auth, model access, browser readiness, workspace paths, and permission mode.',
    note: 'Run this before long, browser-backed, or unattended jobs.',
  },
  {
    name: 'claude-delegate',
    provider: 'Claude Code',
    syntax: '$claude-delegate [fresh-session flags] -- "task prompt"',
    dispatcher: 'delegate --provider claude',
    purpose: 'Start a new Claude Code background session for one delegated task.',
    note: 'Every invocation creates a new job. Use followup to continue the same live session.',
  },
  {
    name: 'claude-status',
    provider: 'Claude Code',
    syntax:
      '$claude-status [--job <id>] [--all] [--json] [--compact] [--limit <n>] [--stored-status <state>]',
    dispatcher: 'status --provider claude',
    purpose: 'List Claude jobs in the current workspace or inspect one job.',
    note: 'Prefer --job <id> --json --compact when an automation already has a job ID.',
  },
  {
    name: 'claude-wait',
    provider: 'Claude Code',
    syntax: '$claude-wait <jobId> [--timeout 5m] [--interval 2s] [--json] [--compact]',
    dispatcher: 'wait',
    purpose: 'Wait until a job finishes, blocks, awaits follow-up, fails, stops, or times out.',
    note: 'A wait timeout does not stop the underlying job.',
  },
  {
    name: 'claude-result',
    provider: 'Claude Code',
    syntax: '$claude-result <jobId> [--partial] [--json] [--compact]',
    dispatcher: 'result',
    purpose: 'Read the clean final result or an explicitly requested partial result.',
    note: 'Without --partial, incomplete output is rejected so scripts do not mistake it for final output.',
  },
  {
    name: 'claude-stop',
    provider: 'Claude Code',
    syntax:
      '$claude-stop <jobId> | $claude-stop --all-awaiting-followup | $claude-stop --all-needs-input',
    dispatcher: 'stop',
    purpose: 'Stop one Claude job or clean up selected groups of idle or blocked jobs.',
    note: 'Stopped jobs remain inspectable and may have a partial result.',
  },
  {
    name: 'claude-followup',
    provider: 'Claude Code',
    syntax: '$claude-followup <jobId> [--all] [--json] -- "next instruction"',
    dispatcher: 'followup',
    purpose: 'Send another turn to an existing live Claude Code session.',
    note: 'Startup-only flags such as --model and --add-dir are rejected because the session already exists.',
  },
  {
    name: 'claude-review',
    provider: 'Claude Code',
    syntax: '$claude-review <jobId> [--blocking|--fail-on <gate>] [--json]',
    dispatcher: 'review',
    purpose: 'Review the latest non-review turn in the same Claude session.',
    note: 'Fast and context-rich, but less independent than adversarial review.',
  },
  {
    name: 'claude-adversarial-review',
    provider: 'Claude Code',
    syntax:
      '$claude-adversarial-review <jobId> [fresh-session flags] [--blocking|--fail-on <gate>]',
    dispatcher: 'adversarial-review',
    purpose: 'Start a fresh independent Claude session to evaluate a completed job result.',
    note: 'Creates another model session and may count toward Claude Code usage.',
  },
  {
    name: 'claude-workflow',
    provider: 'Claude Code',
    syntax: '$claude-workflow [fresh-session flags] -- "workflow prompt"',
    dispatcher: 'workflow',
    purpose: 'Start a dynamic workflow that triggers Claude Code ultracode planning.',
    note: 'Use for multi-step work that benefits from plan-and-execute orchestration.',
  },
  {
    name: 'claude-workflows',
    provider: 'Claude Code',
    syntax: '$claude-workflows [<jobId>] [--all] [--json]',
    dispatcher: 'workflows',
    purpose: 'List or inspect plugin-owned workflow and deep-research sessions.',
    note: 'Read-only and distinct from Claude Code’s session-scoped /workflows TUI panel.',
  },
  {
    name: 'claude-goal',
    provider: 'Claude Code',
    syntax: '$claude-goal [fresh-session flags] -- "goal condition"',
    dispatcher: 'goal',
    purpose: 'Start a background session with a durable /goal condition.',
    note: 'Use a concrete condition that can be evaluated from repository state.',
  },
  {
    name: 'claude-fork',
    provider: 'Claude Code',
    syntax: '$claude-fork [fresh-session flags] -- "directive"',
    dispatcher: 'fork',
    purpose: 'Fork a Claude Code subagent for a focused directive.',
    note: 'Creates a new job and session rather than continuing an existing job.',
  },
  {
    name: 'claude-batch',
    provider: 'Claude Code',
    syntax: '$claude-batch [fresh-session flags] -- "parallelizable instruction"',
    dispatcher: 'batch',
    purpose: 'Run Batch Parallel Work Orchestration for a change that can be decomposed.',
    note: 'Token usage can grow with the number of tasks and parallel agents.',
  },
  {
    name: 'claude-deep-research',
    provider: 'Claude Code',
    syntax: '$claude-deep-research [fresh-session flags] -- "research question"',
    dispatcher: 'deep-research',
    purpose: 'Run multi-agent web research with cross-checked citations.',
    note: 'Requires network-capable Claude tools and can fan out into multiple research agents.',
  },
  {
    name: 'claude-skills',
    provider: 'Claude Code',
    syntax: '$claude-skills [--json]',
    dispatcher: 'skills',
    purpose: 'List project, user, and plugin skills visible to delegated Claude sessions.',
    note: 'Duplicate invocation names are reported as ambiguous rather than silently resolved.',
  },
  {
    name: 'claude-upgrade',
    provider: 'Claude Code',
    syntax: '$claude-upgrade [--dry-run] [--yes] [--json] [--public|--local]',
    dispatcher: 'upgrade',
    purpose: 'Plan or perform a marketplace refresh and plugin reinstall.',
    note: 'Without --yes it only prints the plan. Restart Codex after a successful upgrade.',
  },
  {
    name: 'agy-setup',
    provider: 'Google Antigravity',
    syntax: '$agy-setup [--json]',
    dispatcher: 'agy-setup',
    purpose:
      'Validate the companion plugin, agy interactive surface, exact resume, and PTY runtime.',
    note: 'Checks model access without starting a delegated model turn.',
  },
  {
    name: 'agy-doctor',
    provider: 'Google Antigravity',
    syntax: '$agy-doctor [permission flags] [--json]',
    dispatcher: 'agy-doctor',
    purpose:
      'Preflight exact resume, workspace access, PTY attachment, and native permission handoff.',
    note: 'Read-only; it does not invoke a model task.',
  },
  {
    name: 'agy-delegate',
    provider: 'Google Antigravity',
    syntax: '$agy-delegate [Antigravity flags] -- "task prompt"',
    dispatcher: 'delegate --provider agy',
    purpose: 'Start one supervised persistent Antigravity TUI session.',
    note: 'The driver records the exact UUID and keeps the native conversation alive for follow-up.',
  },
  {
    name: 'agy-status',
    provider: 'Google Antigravity',
    syntax: '$agy-status [--job <id>] [--all] [--json] [--compact] [--limit <n>]',
    dispatcher: 'status --provider agy',
    purpose: 'List Antigravity jobs or inspect one supervised process.',
    note: 'Status resolves plugin-owned records rather than reading supervisor files directly.',
  },
  {
    name: 'agy-attach',
    provider: 'Google Antigravity',
    syntax: '$agy-attach <jobId> [--all]',
    dispatcher: 'attach',
    purpose: 'Attach a user-owned terminal to the persistent native Antigravity TUI.',
    note: 'Permission cards, /agents, /tasks, and /fork stay native; Ctrl+] detaches locally.',
  },
  {
    name: 'agy-wait',
    provider: 'Google Antigravity',
    syntax: '$agy-wait <jobId> [--timeout 5m] [--interval 2s] [--json] [--compact]',
    dispatcher: 'wait',
    purpose: 'Wait for a turn to finish, need input, fail, stop, or time out.',
    note: 'A timeout returns recovery actions and leaves the process running.',
  },
  {
    name: 'agy-result',
    provider: 'Google Antigravity',
    syntax: '$agy-result <jobId> [--partial] [--json] [--compact]',
    dispatcher: 'result',
    purpose: 'Read a normalized transcript result or an explicitly requested partial result.',
    note: 'Raw ANSI TUI and diagnostic logs remain available through action hints.',
  },
  {
    name: 'agy-stop',
    provider: 'Google Antigravity',
    syntax: '$agy-stop <jobId> [--all] [--json] [--compact]',
    dispatcher: 'stop',
    purpose: 'Terminate a supervised Antigravity job and update its stored state.',
    note: 'Use agy-result --partial to read output captured before termination.',
  },
  {
    name: 'agy-followup',
    provider: 'Google Antigravity',
    syntax: '$agy-followup <jobId> [--all] [--json] -- "next instruction"',
    dispatcher: 'followup',
    purpose: 'Continue the exact Antigravity conversation recorded for a job.',
    note: 'Uses the existing persistent PTY and never workspace-global --continue state.',
  },
  {
    name: 'agy-review',
    provider: 'Google Antigravity',
    syntax: '$agy-review <jobId> [--blocking|--fail-on <gate>] [--json]',
    dispatcher: 'review',
    purpose: 'Review the latest non-review turn in the same Antigravity conversation.',
    note: 'Fast and context-rich, but less independent than adversarial review.',
  },
  {
    name: 'agy-adversarial-review',
    provider: 'Google Antigravity',
    syntax: '$agy-adversarial-review <jobId> [Antigravity startup flags]',
    dispatcher: 'adversarial-review --provider agy',
    purpose: 'Review a stored result in a fresh independent Antigravity conversation.',
    note: 'Creates a separate supervised review job with reviewOf metadata.',
  },
  {
    name: 'agy-workflow',
    provider: 'Google Antigravity',
    syntax: '$agy-workflow [Antigravity flags] -- "workflow task"',
    dispatcher: 'workflow --provider agy',
    purpose: 'Run phased multi-agent work with explicit verification and synthesis.',
    note: 'Keeps the native default parent and invokes bundled child profiles; the parent conversation is the job boundary.',
  },
  {
    name: 'agy-goal',
    provider: 'Google Antigravity',
    syntax: '$agy-goal [Antigravity flags] -- "completion condition"',
    dispatcher: 'goal --provider agy',
    purpose: 'Work autonomously toward a concrete condition and verify it before completion.',
    note: 'Continue the same context with agy-followup when another turn is needed.',
  },
  {
    name: 'agy-fork',
    provider: 'Google Antigravity',
    syntax: '$agy-fork [Antigravity flags] -- "directive"',
    dispatcher: 'fork --provider agy',
    purpose: 'Request and verify work from an independent Antigravity subagent.',
    note: 'Uses native subagent tools; TUI /fork instead branches conversations and remains distinct.',
  },
  {
    name: 'agy-batch',
    provider: 'Google Antigravity',
    syntax: '$agy-batch [Antigravity flags] -- "parallelizable instruction"',
    dispatcher: 'batch --provider agy',
    purpose: 'Run independent items concurrently and synthesize an ordered result.',
    note: 'Use only when work items can safely proceed independently.',
  },
  {
    name: 'agy-deep-research',
    provider: 'Google Antigravity',
    syntax: '$agy-deep-research [Antigravity flags] -- "research question"',
    dispatcher: 'deep-research --provider agy',
    purpose: 'Fan out research, prefer primary sources, cross-check claims, and cite links.',
    note: 'Native web permission cards can be reviewed through agy-attach.',
  },
  {
    name: 'agy-workflows',
    provider: 'Google Antigravity',
    syntax: '$agy-workflows [<jobId>] [--all] [--json]',
    dispatcher: 'workflows --provider agy',
    purpose: 'List or inspect recorded workflow, goal, fork, batch, and research jobs.',
    note: 'The report includes an attach command; /agents provides native child inspection and kill.',
  },
  {
    name: 'agy-skills',
    provider: 'Google Antigravity',
    syntax: '$agy-skills [--json]',
    dispatcher: 'skills --provider agy',
    purpose: 'Catalog project, user, and installed-plugin Antigravity skills.',
    note: 'Duplicate names remain visible and explicitly ambiguous.',
  },
  {
    name: 'agy-upgrade',
    provider: 'Google Antigravity',
    syntax: '$agy-upgrade [--dry-run] [--yes] [--json] [--public|--local]',
    dispatcher: 'upgrade',
    purpose: 'Plan or perform a marketplace refresh and plugin reinstall.',
    note: 'Upgrades the Codex plugin, not the agy executable.',
  },
  ...coreLifecycleSkills('pi', 'Pi', 'omp'),
  ...coreLifecycleSkills('qwen', 'Qwen Code', 'qwen'),
];

export const dispatcherCommands = [
  ['setup', 'Environment readiness report'],
  ['agy-setup', 'Antigravity persistent-TUI preflight'],
  ['agy-doctor', 'Antigravity targeted-resume and permission preflight'],
  ['doctor', 'Detailed Claude launch preflight'],
  ['delegate', 'Start a Claude, Antigravity, Pi, or Qwen Code job'],
  ['restart', 'Stop a job and start a fresh replacement'],
  ['workflow', 'Start a provider workflow'],
  ['goal', 'Pursue a provider completion condition'],
  ['fork', 'Request an independent provider subagent'],
  ['batch', 'Start provider batch orchestration'],
  ['deep-research', 'Start multi-agent provider research'],
  ['status', 'List jobs or inspect one job'],
  ['attach', 'Attach to a persistent Antigravity TUI'],
  ['result', 'Read final or partial output'],
  ['wait', 'Wait for a job state transition'],
  ['stop', 'Stop one job or a cleanup group'],
  ['followup', 'Continue an exact provider conversation'],
  ['review', 'Run a same-conversation review'],
  ['adversarial-review', 'Run an independent fresh-conversation review'],
  ['workflows', 'Inspect workflow-like job records'],
  ['skills', 'Inventory provider-visible skills'],
  ['upgrade', 'Plan or execute plugin reinstall'],
  ['version', 'Print the installed plugin version'],
].map(([name, purpose]) => ({ name, purpose, smokeArgs: [name, '--help'] }));
