export const codexSkills = [
  {
    name: 'claude-setup',
    provider: 'Claude Code',
    syntax: '$claude-setup',
    dispatcher: 'setup',
    purpose: 'Check the basic Codex, Node.js, Claude Code, transcript, and follow-up environment.',
    note: 'Read-only. An aggregate warn can be healthy when only the optional Claude daemon probe warns.',
  },
  {
    name: 'claude-doctor',
    provider: 'Claude Code',
    syntax:
      '$claude-doctor [--claude-access] [--real|--chrome|--no-chrome] [permission flags] [--json]',
    dispatcher: 'doctor',
    purpose:
      'Preflight auth, model access, browser readiness, workspace paths, and permission mode.',
    note: 'Run this before long, browser-backed, or unattended jobs.',
  },
  {
    name: 'claude-delegate',
    provider: 'Claude Code',
    syntax: '$claude-delegate [fresh-session flags] -- "task prompt"',
    dispatcher: 'delegate --provider claude',
    purpose: 'Start a new Claude Code background session for one delegated task.',
    note: 'Every invocation creates a new job. Use followup to continue the same live session.',
  },
  {
    name: 'claude-status',
    provider: 'Claude Code',
    syntax:
      '$claude-status [--job <id>] [--all] [--json] [--compact] [--limit <n>] [--stored-status <state>]',
    dispatcher: 'status --provider claude',
    purpose: 'List Claude jobs in the current workspace or inspect one job.',
    note: 'Prefer --job <id> --json --compact when an automation already has a job ID.',
  },
  {
    name: 'claude-wait',
    provider: 'Claude Code',
    syntax: '$claude-wait <jobId> [--timeout 5m] [--interval 2s] [--json] [--compact]',
    dispatcher: 'wait',
    purpose: 'Wait until a job finishes, blocks, awaits follow-up, fails, stops, or times out.',
    note: 'A wait timeout does not stop the underlying job.',
  },
  {
    name: 'claude-result',
    provider: 'Claude Code',
    syntax: '$claude-result <jobId> [--partial] [--json] [--compact]',
    dispatcher: 'result',
    purpose: 'Read the clean final result or an explicitly requested partial result.',
    note: 'Without --partial, incomplete output is rejected so scripts do not mistake it for final output.',
  },
  {
    name: 'claude-stop',
    provider: 'Claude Code',
    syntax:
      '$claude-stop <jobId> | $claude-stop --all-awaiting-followup | $claude-stop --all-needs-input',
    dispatcher: 'stop',
    purpose: 'Stop one Claude job or clean up selected groups of idle or blocked jobs.',
    note: 'Stopped jobs remain inspectable and may have a partial result.',
  },
  {
    name: 'claude-followup',
    provider: 'Claude Code',
    syntax: '$claude-followup <jobId> [--all] [--json] -- "next instruction"',
    dispatcher: 'followup',
    purpose: 'Send another turn to an existing live Claude Code session.',
    note: 'Startup-only flags such as --model and --add-dir are rejected because the session already exists.',
  },
  {
    name: 'claude-review',
    provider: 'Claude Code',
    syntax: '$claude-review <jobId> [--blocking|--fail-on <gate>] [--json]',
    dispatcher: 'review',
    purpose: 'Review the latest non-review turn in the same Claude session.',
    note: 'Fast and context-rich, but less independent than adversarial review.',
  },
  {
    name: 'claude-adversarial-review',
    provider: 'Claude Code',
    syntax:
      '$claude-adversarial-review <jobId> [fresh-session flags] [--blocking|--fail-on <gate>]',
    dispatcher: 'adversarial-review',
    purpose: 'Start a fresh independent Claude session to evaluate a completed job result.',
    note: 'Creates another model session and may count toward Claude Code usage.',
  },
  {
    name: 'claude-workflow',
    provider: 'Claude Code',
    syntax: '$claude-workflow [fresh-session flags] -- "workflow prompt"',
    dispatcher: 'workflow',
    purpose: 'Start a dynamic workflow that triggers Claude Code ultracode planning.',
    note: 'Use for multi-step work that benefits from plan-and-execute orchestration.',
  },
  {
    name: 'claude-workflows',
    provider: 'Claude Code',
    syntax: '$claude-workflows [<jobId>] [--all] [--json]',
    dispatcher: 'workflows',
    purpose: 'List or inspect plugin-owned workflow and deep-research sessions.',
    note: 'Read-only and distinct from Claude Code’s session-scoped /workflows TUI panel.',
  },
  {
    name: 'claude-goal',
    provider: 'Claude Code',
    syntax: '$claude-goal [fresh-session flags] -- "goal condition"',
    dispatcher: 'goal',
    purpose: 'Start a background session with a durable /goal condition.',
    note: 'Use a concrete condition that can be evaluated from repository state.',
  },
  {
    name: 'claude-fork',
    provider: 'Claude Code',
    syntax: '$claude-fork [fresh-session flags] -- "directive"',
    dispatcher: 'fork',
    purpose: 'Fork a Claude Code subagent for a focused directive.',
    note: 'Creates a new job and session rather than continuing an existing job.',
  },
  {
    name: 'claude-batch',
    provider: 'Claude Code',
    syntax: '$claude-batch [fresh-session flags] -- "parallelizable instruction"',
    dispatcher: 'batch',
    purpose: 'Run Batch Parallel Work Orchestration for a change that can be decomposed.',
    note: 'Token usage can grow with the number of tasks and parallel agents.',
  },
  {
    name: 'claude-deep-research',
    provider: 'Claude Code',
    syntax: '$claude-deep-research [fresh-session flags] -- "research question"',
    dispatcher: 'deep-research',
    purpose: 'Run multi-agent web research with cross-checked citations.',
    note: 'Requires network-capable Claude tools and can fan out into multiple research agents.',
  },
  {
    name: 'claude-skills',
    provider: 'Claude Code',
    syntax: '$claude-skills [--json]',
    dispatcher: 'skills',
    purpose: 'List project, user, and plugin skills visible to delegated Claude sessions.',
    note: 'Duplicate invocation names are reported as ambiguous rather than silently resolved.',
  },
  {
    name: 'claude-upgrade',
    provider: 'Claude Code',
    syntax: '$claude-upgrade [--dry-run] [--yes] [--json] [--public|--local]',
    dispatcher: 'upgrade',
    purpose: 'Plan or perform a marketplace refresh and plugin reinstall.',
    note: 'Without --yes it only prints the plan. Restart Codex after a successful upgrade.',
  },
  {
    name: 'agy-setup',
    provider: 'Google Antigravity',
    syntax: '$agy-setup [--json]',
    dispatcher: 'agy-setup',
    purpose: 'Check agy binary and print-mode availability without spending model tokens.',
    note: 'Authentication is deferred until the first real delegation.',
  },
  {
    name: 'agy-delegate',
    provider: 'Google Antigravity',
    syntax: '$agy-delegate [Antigravity flags] -- "task prompt"',
    dispatcher: 'delegate --provider agy',
    purpose: 'Start one supervised agy --print process.',
    note: 'Print mode is single-turn; start another job for the next instruction.',
  },
  {
    name: 'agy-status',
    provider: 'Google Antigravity',
    syntax: '$agy-status [--job <id>] [--all] [--json] [--compact] [--limit <n>]',
    dispatcher: 'status --provider agy',
    purpose: 'List Antigravity jobs or inspect one supervised process.',
    note: 'Status resolves plugin-owned records rather than reading supervisor files directly.',
  },
  {
    name: 'agy-wait',
    provider: 'Google Antigravity',
    syntax: '$agy-wait <jobId> [--timeout 5m] [--interval 2s] [--json] [--compact]',
    dispatcher: 'wait',
    purpose: 'Wait for an Antigravity process to finish, fail, stop, or time out.',
    note: 'A timeout returns recovery actions and leaves the process running.',
  },
  {
    name: 'agy-result',
    provider: 'Google Antigravity',
    syntax: '$agy-result <jobId> [--partial] [--json] [--compact]',
    dispatcher: 'result',
    purpose: 'Read clean supervised stdout as a final or partial result.',
    note: 'Diagnostic stderr remains available through the job’s log action hint.',
  },
  {
    name: 'agy-stop',
    provider: 'Google Antigravity',
    syntax: '$agy-stop <jobId> [--all] [--json] [--compact]',
    dispatcher: 'stop',
    purpose: 'Terminate a supervised Antigravity job and update its stored state.',
    note: 'Use agy-result --partial to read output captured before termination.',
  },
];

export const dispatcherCommands = [
  ['setup', 'Environment readiness report'],
  ['agy-setup', 'Antigravity print-mode preflight'],
  ['doctor', 'Detailed Claude launch preflight'],
  ['delegate', 'Start a Claude or Antigravity job'],
  ['restart', 'Stop a job and start a fresh replacement'],
  ['workflow', 'Start an ultracode workflow'],
  ['goal', 'Start a /goal session'],
  ['fork', 'Start a forked subagent directive'],
  ['batch', 'Start batch parallel orchestration'],
  ['deep-research', 'Start a /deep-research session'],
  ['status', 'List jobs or inspect one job'],
  ['result', 'Read final or partial output'],
  ['wait', 'Wait for a job state transition'],
  ['stop', 'Stop one job or a cleanup group'],
  ['followup', 'Continue an existing Claude session'],
  ['review', 'Run a same-session review'],
  ['adversarial-review', 'Run an independent fresh-session review'],
  ['workflows', 'Inspect workflow-like job records'],
  ['skills', 'Inventory Claude Code skills'],
  ['upgrade', 'Plan or execute plugin reinstall'],
  ['version', 'Print the installed plugin version'],
].map(([name, purpose]) => ({ name, purpose, smokeArgs: [name, '--help'] }));
